const EXERCISE_CATEGORIES = Object.freeze([
  "Cardio",
  "Strength",
  "Freehand",
  "Gym",
  "Sports",
  "Flexibility",
]);

const EXERCISES = Object.freeze([
  {
    id: "walking-brisk",
    name: "Brisk Walking",
    category: "Cardio",
    workoutType: "cardio",
    equipment: "None",
    targetMuscles: ["Legs", "Core"],
    met: 3.8,
    calculationMethod: "duration",
  },
  {
    id: "running",
    name: "Running",
    category: "Cardio",
    workoutType: "cardio",
    equipment: "None",
    targetMuscles: ["Legs", "Core"],
    met: 9.8,
    calculationMethod: "duration",
  },
  {
    id: "cycling-moderate",
    name: "Cycling",
    category: "Cardio",
    workoutType: "cardio",
    equipment: "Bike",
    targetMuscles: ["Legs"],
    met: 6,
    calculationMethod: "duration",
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    category: "Cardio",
    workoutType: "cardio",
    equipment: "Machine",
    targetMuscles: ["Back", "Legs", "Core"],
    met: 7,
    calculationMethod: "duration",
  },
  {
    id: "stair-climber",
    name: "Stair Climber",
    category: "Cardio",
    workoutType: "cardio",
    equipment: "Machine",
    targetMuscles: ["Legs", "Glutes"],
    met: 8.8,
    calculationMethod: "duration",
  },
  {
    id: "push-ups",
    name: "Push Ups",
    category: "Freehand",
    workoutType: "strength",
    equipment: "Bodyweight",
    targetMuscles: ["Chest", "Shoulders", "Triceps"],
    met: 8,
    calculationMethod: "sets_reps",
  },
  {
    id: "squats-bodyweight",
    name: "Bodyweight Squats",
    category: "Freehand",
    workoutType: "strength",
    equipment: "Bodyweight",
    targetMuscles: ["Legs", "Glutes"],
    met: 5.5,
    calculationMethod: "sets_reps",
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "Freehand",
    workoutType: "cardio",
    equipment: "Bodyweight",
    targetMuscles: ["Full Body"],
    met: 10,
    calculationMethod: "sets_reps",
  },
  {
    id: "plank",
    name: "Plank",
    category: "Freehand",
    workoutType: "flexibility",
    equipment: "Bodyweight",
    targetMuscles: ["Core"],
    met: 3.3,
    calculationMethod: "duration",
  },
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    category: "Freehand",
    workoutType: "cardio",
    equipment: "Bodyweight",
    targetMuscles: ["Full Body"],
    met: 8,
    calculationMethod: "duration",
  },
  {
    id: "bench-press",
    name: "Bench Press",
    category: "Gym",
    workoutType: "strength",
    equipment: "Barbell",
    targetMuscles: ["Chest", "Triceps"],
    met: 5,
    calculationMethod: "sets_reps",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "Gym",
    workoutType: "strength",
    equipment: "Barbell",
    targetMuscles: ["Back", "Legs", "Core"],
    met: 6,
    calculationMethod: "sets_reps",
  },
  {
    id: "barbell-squat",
    name: "Barbell Squat",
    category: "Gym",
    workoutType: "strength",
    equipment: "Barbell",
    targetMuscles: ["Legs", "Glutes"],
    met: 6,
    calculationMethod: "sets_reps",
  },
  {
    id: "bicep-curls",
    name: "Bicep Curls",
    category: "Gym",
    workoutType: "strength",
    equipment: "Dumbbell",
    targetMuscles: ["Biceps"],
    met: 4,
    calculationMethod: "sets_reps",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Gym",
    workoutType: "strength",
    equipment: "Machine",
    targetMuscles: ["Back", "Biceps"],
    met: 5,
    calculationMethod: "sets_reps",
  },
  {
    id: "strength-circuit",
    name: "Strength Circuit",
    category: "Strength",
    workoutType: "strength",
    equipment: "Mixed",
    targetMuscles: ["Full Body"],
    met: 6.5,
    calculationMethod: "duration",
  },
  {
    id: "kettlebell-swings",
    name: "Kettlebell Swings",
    category: "Strength",
    workoutType: "strength",
    equipment: "Kettlebell",
    targetMuscles: ["Posterior Chain", "Core"],
    met: 8,
    calculationMethod: "sets_reps",
  },
  {
    id: "football",
    name: "Football",
    category: "Sports",
    workoutType: "sports",
    equipment: "Ball",
    targetMuscles: ["Full Body"],
    met: 7,
    calculationMethod: "duration",
  },
  {
    id: "basketball",
    name: "Basketball",
    category: "Sports",
    workoutType: "sports",
    equipment: "Ball",
    targetMuscles: ["Full Body"],
    met: 6.5,
    calculationMethod: "duration",
  },
  {
    id: "badminton",
    name: "Badminton",
    category: "Sports",
    workoutType: "sports",
    equipment: "Racket",
    targetMuscles: ["Full Body"],
    met: 5.5,
    calculationMethod: "duration",
  },
  {
    id: "yoga",
    name: "Yoga",
    category: "Flexibility",
    workoutType: "flexibility",
    equipment: "Mat",
    targetMuscles: ["Core", "Hips", "Back"],
    met: 2.8,
    calculationMethod: "duration",
  },
  {
    id: "dynamic-stretching",
    name: "Dynamic Stretching",
    category: "Flexibility",
    workoutType: "flexibility",
    equipment: "None",
    targetMuscles: ["Full Body"],
    met: 2.5,
    calculationMethod: "duration",
  },
  {
    id: "pilates",
    name: "Pilates",
    category: "Flexibility",
    workoutType: "flexibility",
    equipment: "Mat",
    targetMuscles: ["Core", "Back", "Glutes"],
    met: 3.2,
    calculationMethod: "duration",
  },
]);

const EXERCISE_MAP = Object.freeze(
  EXERCISES.reduce((acc, exercise) => {
    acc[exercise.id] = exercise;
    return acc;
  }, {}),
);

module.exports = {
  EXERCISE_CATEGORIES,
  EXERCISES,
  EXERCISE_MAP,
};
